### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Fastidious** [ibrado/jekyll-stickyposts#1]
Followed instructions by installing gem. Added `sticky: true` on front-matter. Added:
```
plugins:
  - jekyll-stickyposts
```
Added:
```
pagination:
    sort_field: "date"
    sort_reverse: false
```
Because I am using `jekyll-paginate`. The post marked as sticky is not at the top. During build time, I get:

```
[…]
      Generating...
       StickyPosts: [posts] 1 post(s) pinned
                    done in 0.688 seconds.
[…]
```
So, it is doing something, not what it is expected.

**Comment by Fastidious** [comment]
Fixed. I had to use:
```
{% assign sorted = site.posts | sort: "stickiness" %}
{% for post in sorted %}
[…]
{% endfor %}
```

**Comment by ibrado** [comment]
I'll update the wording in the docs as only [jekyll-paginate-v2](https://github.com/sverrirs/jekyll-paginate-v2) supports sorting, not the original jekyll-paginate. Thanks...

**Comment by ibrado** [comment]
Hi @Fastidious, I think that should be `paginator.posts` not `site.posts` in your case...

**Comment by Fastidious** [comment]
@ibrado yes, I noticed that is wasn't paginating, and changed it. That is another thing that wasn't on the README. Thanks for the heads up, and the plugin, it is awesome!

**Comment by ibrado** [comment]
Thanks! :) .. I've already updated the README for no, original, and v2 pagination.

**Comment by Ynjxsjmh** [comment]
Facing the same problem, I not only add `gem 'jekyll-stickyposts'` in my Gemfile, but also append `jekyll-stickyposts` to plugins var in _config.yml. It shows `StickyPosts: [posts] 1 post(s) pinned` in the console, but the sticky post is not in the first page but where it normally would.

What code I write is
```
{% assign sorted = paginator.posts | sort: "stickiness" %}
{% for post in sorted %}
  {% if post.sticky %}
    <span class="sticky"><i class="fa fa-thumb-tack" aria-hidden="true"></i></span>
  {% endif %}
  […]
{% endfor %}
```
It has a pinned icon beside the sticky post, but the post is not in the first page. 

It's really strange that the sticky post is logically the first post(It is the first post in variable `site.posts`), thought it didn't appear in the first page.



Your site has an example on this but it seems that you doesn't host the source code of your site in Github. It would be much better if there is a live demo. I also tried to find some in `Used by` but with no luck.
